// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace ExtendedStorage {
    [GeneratedCode("DefGenerator.tt","0.1")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
	public static partial class GeneratedDefs {
		public static class @keyed {
			/// <summary>
			/// Get's the translation key for '<em>Currently storing: {0}</em>'
			/// </summary>
			public const string @ExtendedStorage_CurrentlyStoring = "ExtendedStorage.CurrentlyStoring";
			/// <summary>
			/// Get's the translation key for '<em>Nothing</em>'
			/// </summary>
			public const string @ExtendedStorage_Nothing = "ExtendedStorage.Nothing";
			/// <summary>
			/// Get's the translation key for '<em>∑ {0}</em>'
			/// </summary>
			public const string @ExtendedStorage_TotalCount = "ExtendedStorage.TotalCount";
			/// <summary>
			/// Get's the translation key for '<em>{0}+</em>'
			/// </summary>
			public const string @ExtendedStorage_MultipleQualities = "ExtendedStorage.MultipleQualities";
			/// <summary>
			/// Get's the translation key for '<em>Rename this {0}.</em>'
			/// </summary>
			public const string @ExtendedStorage_Rename = "ExtendedStorage.Rename";
		}
	}
}
