// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace ExtendedStorage {
	[GeneratedCode("Defs.Generated.tt","0.1")]
	[SuppressMessage("ReSharper", "InconsistentNaming")]
	[SuppressMessage("ReSharper", "UnusedMember.Global")]
	public partial class DefNames {
		public const string @Stat_ES_StorageFactor = @"ES.StorageFactor";
		public const string @StatCategory_ExtendedStorage = @"ExtendedStorage";
	}
	[GeneratedCode("Defs.Generated.tt","0.1")]
	[SuppressMessage("ReSharper", "InconsistentNaming")]
	[SuppressMessage("ReSharper", "UnusedMember.Global")]
	public partial class DefReferences {
		private static RimWorld.StatDef _Stat_ES_StorageFactor = Verse.DefDatabase<RimWorld.StatDef>.GetNamed(DefNames.Stat_ES_StorageFactor);
		private static RimWorld.StatCategoryDef _StatCategory_ExtendedStorage = Verse.DefDatabase<RimWorld.StatCategoryDef>.GetNamed(DefNames.StatCategory_ExtendedStorage);
		public static RimWorld.StatDef @Stat_ES_StorageFactor { get { return _Stat_ES_StorageFactor; } }
		public static RimWorld.StatCategoryDef @StatCategory_ExtendedStorage { get { return _StatCategory_ExtendedStorage; } }
	}
}
